[sources.file]
    type = "file" 
    ignore_older = 600 
    include = ["/var/*.log"] 

[transforms.json_parser]
  type = "json_parser" 
  inputs = ["file"] 
  drop_field = true 
  drop_invalid = true 
  field = "message"
  overwrite_target = false
  target_field = "root_field"

[sinks.elk_out]
    type = "elasticsearch" 
    inputs = ["json_parser"] 
    endpoint = "http://elasticsearch:9200"
    healthcheck = true
    index = "twitterapi-%F"
    compression = "none" 